### ISSUE TITLE
Option to only update the root tsconfig

### ISSUE THREAD

**Issue by baptisteArno** [eBayClassifiedsGroup/update-ts-references#40]
I am using your tool to auto update the reference list on my root tsconfig. This is the only file I need to update in order for my LSP to be aware of all the packages without opening them.

I tried to add this in a `update-ts-references.yaml`:

```
packages:
  - '!**/apps/**'
  - '!**/ee/**'
  - '!**/packages/**'
```

But still, it does not ignore my packages.

**Comment by baptisteArno** [comment]
My bad, my config file had a typo!

**Comment by baptisteArno** [comment]
Oh but then it ignores the package for the root tsconfig references. Then I wonder if there is a way just to update the root tsconfig

**Comment by MKruschke** [comment]
Hi @baptisteArno 👋🏻 
I ask myself why you would not like to have the references updated in the tsconfig's of the packages, because these things are important for language server to get a clue in which order the build needs to be executed and you would loose the benefits that project references offer.

**Comment by baptisteArno** [comment]
Indeed, in the end the language server needs it at a package level as well 👍

Thank you for that great tool
